### PR TITLE
Windows find support

### PR DESCRIPTION
**Pull request by xubaiw**
In this pr I'll refactor the JavaScript part to more maintainable one, as well as implement the find and src feature.

Closes: #30

### CODE REVIEW

**Comment by hargoniX** [comment]
The `.bmp` is actualy done on purpose don't change it please. It's a hack because Github pages will use `gzip` compression for `.bmp` data automatically but not for `.json` one.

**Comment by xubaiw** [comment]
Is usage of `XMLHttpRequest` also intended?

**Comment by hargoniX** [comment]
The JS is just fully taken over from doc-gen3 as well, if you think there are more idiomatic ways we could get stuff done feel free as long as you don't pull in too many external dependencies.

**Comment by xubaiw** [comment]
Both find and src endpoint are available now. But with a slightly different syntax:

- `/find/#mul_le_mul` -> `/Mathlib/Init/Data/Int/Order.html#Int.mul_le_mul`
- `/find/#mul_le_mul/src` -> `https://github.com/leanprover-community/mathlib4/blob/b6afb0dfcaeee607ddd20f38373d2f1419b517c8/Mathlib/Init/Data/Int/Order.lean#L641-L645`

I uses the default fuzzy match, but if you want we can switch to exact find.

**Comment by xubaiw** [comment]
> The JS is just fully taken over from doc-gen3 as well, if you think there are more idiomatic ways we could get stuff done feel free as long as you don't pull in too many external dependencies.

No external dependencies. These codes are quite messy, and use lots of legacy features. I used to think it's to support IE, but `Promise` code cannot even run on IE.

**Comment by xubaiw** [comment]
Both `/find?pattern=Nat.add#doc` and `/find/#doc/Nat.add` can work now.

However, for the first syntax, some servers cannot recognize `/find` as directory and will return `404`. I'm not sure what's the behavior of GitHub Pages.

For this situation, just changing it to `/find/?pattern=Nat.add#doc` will get things work.

**Comment by hargoniX** [comment]
Works!

**Pull request merged**
