### PR TITLE
LeanInk Integration

### LINKED ISSUE #10: Integration with LeanInk
Integrating with https://github.com/insightmind/LeanInk would be very useful for proof exploration.

### PR DESCRIPTION
**Pull request by xubaiw**
close #10

### CODE REVIEW

**Comment by xubaiw** [comment]
Currently blocked by LeanInk not compatible with newer lean version

**Comment by hargoniX** [comment]
Ah very nice, I was gonna start looking into this next week as well but its of course perfectly fine if you handle it^^

A thing that would be important to me, is that we hide the LeanInk integration behind a flag, after all it depends on Alectryon which requires python which in turn is not necessarily part of a Lean development environment.

**Comment by xubaiw** [comment]
That's not true. LeanInk itself is a pure Lean application which analyzes and annotates the source code. So we can substitute the Alectryon part (json of analysis result -> html) with our own code.

**Comment by Kha** [comment]
Right, using doc-gen4's HTML formatting instead of Alectryon is a very real possibility that would avoid the Python dependency as well as make it easier to add Lean-specific extensions in the future. It would be nice to keep compatibility with Alectryon, but this does look like the more promising path for the future. /cc @leodemoura @gebner

**Comment by hargoniX** [comment]
Ah that's of course very much possible as well, I was just under the impression replicating Alectryon would be a rather non trivial thing to do. In that case we could even add links back to the generated doc-gen pages about the types etc. that show up in proofs which would be pretty cool.

**Comment by insightmind** [comment]
I think both options have benefits and drawbacks.
Implementing our solution for rendering the source code to HTML makes sense as it removes the issue of having additional dependencies outside the lean ecosystem. It also allows us to implement features that are more specific to Lean and move forward at a faster pace.
Replicating Alectryon is probably not necessary for this use case. Alectryon offers many different features for customization and control of the output, which is perhaps unnecessary for the usage in doc-gen.

> In that case, we could even add links back to the generated doc-gen pages about the types etc. that show up in proofs which would be pretty cool.

Defining links is also now possible with the changes we made to Alectryon. The updated model we implemented within Alectryon defines a `link` property for each `Token`. Setting this value causes Alectryon to render the token as a button instead of plain text. We should be able to add links during LeanInks output. However, we need a way for LeanInk to figure out how to generate the URLs for types, etc., when using this approach.

> Currently blocked by LeanInk not compatible with newer lean version

We should probably discuss how to move forward with supporting Lean 4 versions because ensuring that all tools always support the latest nightly build is clearly a demanding process. One option would be only to provide support for the latest milestone release, but that does only make sense if they're released regularly. @Kha, what's your opinion on this?

**Comment by Kha** [comment]
That's a great question. Right now I think the nightly releases make the most sense for "heavy" use of Lean, so I don't have a better strategy in mind than fixing dependencies when someone notices an incompatibility.

Btw, I didn't actually find an incompatibility between LeanInk and Lean master.

**Comment by xubaiw** [comment]
Anyway, there is now no conflict between them in the latest commits. I'll try to work out a simple page this weekend.

**Comment by xubaiw** [comment]
Is there anyway to accelerate LeanInk analysis? Current implementation is to run the analysis separately for each file and it takes more than one hour to generate doc for doc-gen4 itself. Most of the time comes from analyzing `Lean`, `Init`, `Std` and `Lake`.

Can I elab all the file together once and get information from the single `Environment`?

**Comment by xubaiw** [comment]
Another issue when I test it on mathlib4 is that LeanInk try to evaluate `initialize` in the same module. but I have no idea why this happens.

```lean
libc++abi: terminating with uncaught exception of type lean::exception: cannot evaluate `[init]` declaration 'Mathlib.Prelude.Rename.renameExtension' in the same module
zsh: abort      ~/doc-gen4/build/bin/doc-gen4 Mathlib
```

**Comment by hargoniX** [comment]
> That's a great question. Right now I think the nightly releases make the most sense for "heavy" use of Lean, so I don't have a better strategy in mind than fixing dependencies when someone notices an incompatibility.

Regarding nightly usage etc. Are we planning on eventually shipping a doc-gen build with Lean via `elan`? That would obviously make usage *a lot* easier than having to download and compile yourself etc.

**Comment by Kha** [comment]
I don't know where the threshold should be, but we probably don't want to ship *every* tool with Lean by default. Even the clang toolchain would ideally be optional. Rustup has a system for managing these optional components, but that code has been removed from elan, and I'm not sure how much it (and our infrastructure) would have to be changed in order to apply it to elan.

**Comment by hargoniX** [comment]
Continued in #56, as discussed with Kha the approach chosen here will not work without quite a bit of additional effort.

**Pull request closed without merging**
