### PR TITLE
feat: only linkify lean code

### PR DESCRIPTION
**Pull request by alexjbest**
When linkifying code blocks in markdown comments we check that the language of the code block isn't explicitly set to something other than Lean.

E.g.
````
```julia
add(1, 1)
```
````
should not link to the lean definition of `add` in the docs.

We do this by checking that any `class` attribute of the form `language-...` on the code block is `language-lean` (or that there are none, so the default remains that code blocks are lean code)

### CODE REVIEW

**Comment by alexjbest** [comment]
This looks like this might have some serious performance issues right now, I'm investigating

**Comment by hargoniX** [comment]
The pipeline is failing because of some git details :/, I was hoping to get comparable numbers.

**Comment by Kha** [comment]
You'll probably want `github.ref` instead of `github.event.pull_request.head.sha`

**Comment by hargoniX** [comment]
Based on the CI log it looks to me like the issue is that the github URL is getting set to my repo instead of Alex'? It says:
```
cloning https://github.com/leanprover/doc-gen4 to ./lean_packages/doc-gen4
```
When it should be cloning Alex' repo, so the question to me seems which variable allows me to assemble the URL of the fork.

**Comment by Kha** [comment]
See https://docs.github.com/en/actions/learn-github-actions/contexts#github-context, `github.ref` is a ref in your repo

**Review by eric-wieser — APPROVED** [review]

**Comment by hargoniX** [comment]
Manually merged.

**Comment by hargoniX** [comment]
Performance in CI did not degrade.
- Previous run: https://github.com/leanprover-community/mathlib4_docs/actions/runs/6131893206/job/16642276764
- Run with this: https://github.com/leanprover-community/mathlib4_docs/actions/runs/6133285387/job/16645001963

**Pull request merged**
