### PR TITLE
Add comment to README about need for copying css and js files.

### PR DESCRIPTION
**Pull request by jeremysalwen**

### CODE REVIEW

**Comment by hargoniX** [comment]
Maybe note that you can alternatively do a full recompilation?

**Comment by jeremysalwen** [comment]
How would you do that?

**Comment by hargoniX** [comment]
`lake clean` to delete the `build` folder and the `lake build` again (both in the doc-gen4 chekcout of course)

**Comment by jeremysalwen** [comment]
Thank you! I updated the PR.

**Pull request merged**
